name: Android CI/CD

on:
  push:
    tags:        
      - v[0-9].[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gordinmitya/android-ndk
    steps:
      - name: Prepare
        run: apt update && apt install -y ruby-full unzip git-lfs
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download SNPE library
        run: wget -q -P snpe/libs ${{ secrets.SNPE_AAR_LINK }}
      - name: Decrypt and unzip keys
        run: |
          echo "${{ secrets.SECRET_ZIP }}" | base64 -d > secure.zip
          unzip secure.zip
      - name: Install fastlane
        run: |
          gem install bundler
          bundle install
          fastlane init
      - name: Beta
        env:
          JKS_STORE_PASS: ${{ secrets.JKS_STORE_PASS }}
          JKS_KEY_PASS: ${{ secrets.JKS_KEY_PASS }}
        run: fastlane beta